---
title: "Lectures"
description: Computational Neuroscience
output:
  html_document:
    toc: false 
    theme: cosmo
fontsize: 14pt
---

## Introduction to Python programming

- Week 1
    - <a href="lectures/week_01/lecture_variable_assignment.html" target="_blank">Variable Assignment and Data Types in Python</a>
    - <a href="lectures/week_01/lecture_container_types.html" target="_blank">Container Variable Types in Python and Accessing Elements</a>
    - <a href="lectures/week_01/lecture_functions.html" target="_blank">Creating and Calling Functions in Python</a>
    - <a href="lectures/week_01/lecture_type_coercion.html" target="_blank">Type Coercion in Python</a>
    - <a href="lectures/week_01/lecture_loops_cond_flow.html" target="_blank">Loops and Conditional Flow in Python</a>
    - <a href="lectures/week_01/lecture_getting_help.html" target="_blank">Getting Help with Python Programming</a>
    - <a href="lectures/week_01/lecture_mre.html" target="_blank">Creating a Minimal Reproducible Example (MRE)</a>

- Week 2
    - <a href="lectures/week_02/lecture_array_basics.html" target="_blank">NumPy Array Basics</a>
    - <a href="lectures/week_02/lecture_creating_arrays.html" target="_blank">Creating Numpy Arrays</a>
    - <a href="lectures/week_02/lecture_indexing_slicing.html" target="_blank">Indexing and Slicing in NumPy</a>
    - <a href="lectures/week_02/lecture_element_vs_aggregate.html" target="_blank">Element-wise vs Aggregate Operations in NumPy</a>
    - <a href="lectures/week_02/lecture_broadcasting.html" target="_blank">Broadcasting in NumPy</a>
    - <a href="lectures/week_02/lecture_reshape_transpose.html" target="_blank">Reshaping and Transposing Arrays</a>
    - <a href="lectures/week_02/lecture_basic_stats.html" target="_blank">Basic Statistics with NumPy</a>

- Week 3
    - <a href="lectures/week_03/lecture_intro_to_matplotlib.html" target="_blank">Introduction to Matplotlib</a>
    - <a href="lectures/week_03/lecture_basic_plotting.html" target="_blank">Basic Plotting with Matplotlib</a>
    - <a href="lectures/week_03/lecture_subplots.html" target="_blank">Multiple Plots in One Figure (Subplots)</a>
    - <a href="lectures/week_03/lecture_plot_types.html" target="_blank">Exploring Different Types of Plots with Matplotlib</a>
    - <a href="lectures/week_03/lecture_plot_vs_axis.html" target="_blank">A closer look at the Matplotlib Hierarchy</a>

## Introduction to dynamical systems
- Week 4
    - <a href="lectures/week_04/lecture_functions_and_graphs.html" target="_blank">Functions and Graphs</a>
    - <a href="lectures/week_04/lecture_derivatives.html" target="_blank">The Derivative of a Function</a>
    - <a href="lectures/week_04/lecture_integrals.html" target="_blank">The Integral of a Function</a>
    - <a href="lectures/week_04/lecture_fundamental_theorem.html" target="_blank">The Fundamental Theorem of Calculus</a>

- Week 5
    - <a href="lectures/week_05/lecture_diff_eqs.html" target="_blank">Introduction to Differential Equations</a>
    - <a href="lectures/week_05/lecture_eulers_method.html" target="_blank">Introduction to Euler's Method</a>
    - <a href="lectures/week_05/lecture_equilibrium.html" target="_blank">Introduction to Equilibrium</a>
    - <a href="lectures/week_05/lecture_eulers_method_passive_signals.html" target="_blank">Euler's Method: Passive Signals in Neurons</a>

## Models of single neurons
- Week 6
    - <a href="lectures/week_06/lecture_week_6.html" target="_blank">Conductance-based models working towards HH</a>
    - <a href="lectures/week_06/passive_dynamics_K.html" target="_blank">Passive dynamics with potassium</a>
    - <a href="lectures/week_06/passive_two_ion_dynamics.html" target="_blank">Passive dynamics with two ions</a>
    - <a href="lectures/week_06/smooth_na_conductance.html" target="_blank">Smooth sodium conductance</a>
    - <a href="lectures/week_06/active_na_conductance.html" target="_blank">Active sodium conductance</a>
    - <a href="lectures/week_06/active_na_k_conductance.html" target="_blank">Active sodium and potassium conductance</a>
    - <a href="lectures/week_06/active_na_k_leak_conductance.html" target="_blank">Active sodium, potassium, and leak conductance</a>

- Week 7
    - <a href="lectures/week_07/lecture_simple_models.html" target="_blank">Simple models of single neurons</a>
    - <a href="lectures/week_07/simple_models_lif.html" target="_blank">Leaky Integrate-and-Fire model</a>
    - <a href="lectures/week_07/simple_models_qif.html" target="_blank">Quadratic Integrate-and-Fire model</a>
    - <a href="lectures/week_07/simple_models_iz.html" target="_blank">Izhikevich model</a>

## Building networks
- Week 8
    - <a href="lectures/week_08/lecture_psps.html" target="_blank">Modelling Post-Synaptic Potentials</a>
    - <a href="lectures/week_08/lecture_building_networks.html" target="_blank">Connecting neurons into large networks</a>
    - <a href="lectures/week_08/lecture_basal_ganglia.html" target="_blank">Building a network of the basal ganglia</a>
    - <a href="lectures/week_08/lecture_basal_ganglia.html" target="_blank">Basal Ganglia in code</a>

## synaptic plasticity
- Week 9
  - Hebbian Learning
  - Hebbian Spike-Timing-Dependent Plasticity (STDP)

- Week 10
  - Reinforcement Learning
  - Reinforcement Learning in the basal ganglia

- Week 11
  - Supervised Learning
  - Supervised Learning in the cerebellum

## Model from the literature
- Week 12
  - Helpful clues based on tutorial and ilearn questions for
    your final project

- Week 13
  - Helpful clues based on tutorial and ilearn questions for
    your final project
